name: mus
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - lime
  - matplotlib
  - python=3.10
  - pytorch=2.0.1
  - shap
  - torchvision
  - transformers
  - pytorch-cuda=11.7
  - torchaudio
prefix: /home/antonxue/lib/miniconda3/envs/mus
